example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('wishlist/', include('wishlist.urls'))
]

wishlist/urls.py
from django.urls import path
from wishlist.views import *

app_name = 'wishlist'

urlpatterns = [
    path('', show_wishlist, name='show_wishlist'),
    path('ajax/', wishlist_ajax, name='wishlist_ajax'),
    path('ajax/submit/', add_wishlist, name='add_wishlist'),
    path('xml/', show_wishlist_xml, name='show_wishlist_xml'),
    path('json/', show_wishlist_json, name='show_wishlist_json'),
    path('json/<int:id>', find_by_id_json, name='find_by_id_json'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout')
]

example_app/models.py
from django.db import models

# Create your models here.

wishlist/models.py
from django.db import models

# Create your models here.
from django.db import models

class BarangWishlist(models.Model):
    nama_barang = models.CharField(max_length=50)
    harga_barang = models.IntegerField()
    deskripsi = models.TextField()

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

wishlist/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.core import serializers
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from wishlist.models import BarangWishlist
import datetime

# Create your views here.
@login_required(login_url='/wishlist/login/')
def show_wishlist(req):
    data_barang_wishlist = BarangWishlist.objects.all()
    print(data_barang_wishlist)
    context = {
        'list_barang': data_barang_wishlist,
        'nama': 'Bona',
        'last_login': req.COOKIES['last_login'],
    }
    return render(req, "wishlist.html", context)

@login_required(login_url='/wishlist/login/')
def wishlist_ajax(req):
    context = {
        'nama': 'Bona',
        'last_login': req.COOKIES['last_login'],
    }
    return render(req, "wishlist_ajax.html", context)

@login_required(login_url='/wishlist/login/')
@csrf_exempt
def add_wishlist(req):
    if req.method == "POST":
        nama = req.POST.get("nama")
        harga = req.POST.get("harga")
        deskripsi = req.POST.get("deskripsi")
        BarangWishlist.objects.create(nama_barang=nama, harga_barang=harga, deskripsi=deskripsi)
        return HttpResponse()
    else:
        print("here")
        return redirect("wishlist:show_wishlist")

def show_wishlist_xml(req):
    data_barang_wishlist = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("xml", data_barang_wishlist), content_type="application/xml")

def show_wishlist_json(req):
    data_barang_wishlist = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("json", data_barang_wishlist), content_type="application/json")

def find_by_id_json(req, id):
    data = BarangWishlist.objects.filter(pk = id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def register(req):
    form = UserCreationForm()

    if req.method == "POST":
        form = UserCreationForm(req.POST)
        if form.is_valid():
            form.save()
            messages.success(req, 'Akun telah berhasil dibuat!')
            return redirect('wishlist:login')
    
    context = {'form':form}
    return render(req, 'register.html', context)

def login_user(req):
    if req.method == 'POST':
        username = req.POST.get('username')
        password = req.POST.get('password')
        user = authenticate(req, username=username, password=password)
        if user is not None:
            login(req, user)
            response = HttpResponseRedirect(reverse("wishlist:show_wishlist")) # membuat response
            response.set_cookie('last_login', str(datetime.datetime.now())) # membuat cookie last_login dan menambahkannya ke dalam response
            return response
        else:
            messages.info(req, 'Username atau Password salah!')
    context = {}
    return render(req, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('wishlist:login'))
    response.delete_cookie('last_login')
    return response

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  {% endblock content %}
</body>

</html>

wishlist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}

<div class = "login">

    <h1>Login</h1>

    <form method="POST" action="">
        {% csrf_token %}
        <table>
            <tr>
                <td>Username: </td>
                <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
            </tr>
                    
            <tr>
                <td>Password: </td>
                <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
            </tr>

            <tr>
                <td></td>
                <td><input class="btn login_btn" type="submit" value="Login"></td>
            </tr>
        </table>
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}     
        
    Belum mempunyai akun? <a href="{% url 'wishlist:register' %}">Buat Akun</a>

</div>

{% endblock content %}

wishlist/templates/navbar.html
<div class="navbar bg-primary shadow">
  <div class="container-fluid">
    <div class="d-flex w-100 justify-content-between">
      <span class="navbar-brand align-self-center">Wishlist</span>
      <div class="d-flex gap-4">
        <p class="align-self-center m-0">{{nama}}</p>
        <button class="border rounded border-info">
          <a href="{% url 'wishlist:logout' %}" class="text-decoration-none">Logout</a>
        </button>
      </div>
    </div>
  </div>
</div>

wishlist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}  

<div class = "login">
    
    <h1>Formulir Registrasi</h1>  

        <form method="POST" >  
            {% csrf_token %}  
            <table>  
                {{ form.as_table }}  
                <tr>  
                    <td></td>
                    <td><input type="submit" name="submit" value="Daftar"/></td>  
                </tr>  
            </table>  
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}

wishlist/templates/wishlist.html
{% extends 'base.html' %}

{% block meta %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css">
{% endblock meta %}

{% block content %}

{% include 'navbar.html' %}

<div class="p-4">
  <table class="table table-bordered">
      <tr>
      <th>Nama Barang</th>
      <th>Harga Barang</th>
      <th>Deskripsi</th>
      </tr>
      {% comment %} Tambahkan data di bawah baris ini {% endcomment %}
      {% for barang in list_barang %}
          <tr>
              <td>{{barang.nama_barang}}</td>
              <td>{{barang.harga_barang}}</td>
              <td>{{barang.deskripsi}}</td>
          </tr>
      {% endfor %}
  </table>
  <h5>Sesi terakhir login: {{ last_login }}</h5>
</div>

{% endblock content %}

wishlist/templates/wishlist_ajax.html
{% extends 'base.html' %}

{% block meta %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
  function updateTable(){
    $.get("http://localhost:8000/wishlist/json/", function(data) {
      // fill table
      for(var i = 0; i < data.length; i++){
        var tr = document.createElement("tr");
        var tdNama = document.createElement("td");
        tdNama.append(data[i].fields.nama_barang);
        var tdHarga = document.createElement("td");
        tdHarga.append(data[i].fields.harga_barang);
        var tdDeskripsi = document.createElement("td");
        tdDeskripsi.append(data[i].fields.deskripsi);
        
        tr.append(tdNama);
        tr.append(tdHarga);
        tr.append(tdDeskripsi);
        
        $(".table").append(tr);
      }
    });
  }
  
  $(document).ready(function(){
    updateTable();
    
    $("#add_wishlist").click(function(){
      var nama = $("#input_nama").val();
      var harga = $("#input_harga").val();
      var deskripsi = $("#input_deskripsi").val();

      $.post("http://localhost:8000/wishlist/ajax/submit/",
      {
        nama,
        harga,
        deskripsi,
      },
      function(data, status){
        console.log("add wishlist success");

        var tr = document.createElement("tr");
        var tdNama = document.createElement("td");
        tdNama.append(nama);
        var tdHarga = document.createElement("td");
        tdHarga.append(harga);
        var tdDeskripsi = document.createElement("td");
        tdDeskripsi.append(deskripsi);
        
        tr.append(tdNama);
        tr.append(tdHarga);
        tr.append(tdDeskripsi);
        
        $(".table").append(tr);

        $("#input_nama").val("");
        $("#input_harga").val("");
        $("#input_deskripsi").val("");
      });
    });
  });
</script>
{% endblock meta %}

{% block content %}

{% include 'navbar.html' %}

<div class="p-4">
  <table class="table table-bordered">
      <tr>
        <th>Nama Barang</th>
        <th>Harga Barang</th>
        <th>Deskripsi</th>
      </tr>
  </table>
  <h5>Sesi terakhir login: {{ last_login }}</h5>

  <h5 class="mt-4">Tambah Barang</h5>
  <form method="POST" action="">
    {% csrf_token %}
    <table>
      <tr>
          <td>Nama Barang: </td>
          <td><input type="text" name="nama_barang" placeholder="Nama Barang" class="form-control" id="input_nama"></td>
      </tr>
      <tr>
          <td>Harga Barang: </td>
          <td><input type="text" name="harga_barang" placeholder="Harga Barang" class="form-control" id="input_harga"></td>
      </tr>
      <tr>
          <td>Deskripsi: </td>
          <td><input type="text" name="deskripsi" placeholder="Deskripsi" class="form-control" id="input_deskripsi"></td>
      </tr>
      </table>
    </form>
    <button id="add_wishlist" class="btn border rounded bg-info">Tambah</button>
</div>

{% endblock content %}